spring:
  datasource:
    url: jdbc:mysql://18.190.99.173:3306/demoa
    username: root
    password: duolaameng
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  configuration:
    map-underscore-to-camel-case: true
    use-generated-keys: true
